// Generated by CoffeeScript 1.4.0
(function() {
	var config, env, path, rootPath;

	path = require('path');

	rootPath = path.normalize(__dirname + '/..');

	env = process.env.NODE_ENV || 'development';

	config = {
		development: {
			root: rootPath,
			app: {
				name: 'project'
			},
			port: 3000,
			db: 'mongodb://localhost/project-development'
		},
		test: {
			root: rootPath,
			app: {
				name: 'project'
			},
			port: 3000,
			db: 'mongodb://localhost/project-test'
		},
		production: {
			root: rootPath,
			app: {
				name: 'project'
			},
			port: 3000,
			db: 'mongodb://localhost/project-production'
		}
	};

	module.exports = config[env];

}).call(this);
