// Generated by CoffeeScript 1.4.0
(function() {
	var Car, express, mongoose, router;

	express = require('express');

	router = express.Router();

	mongoose = require('mongoose');

	Car = mongoose.model('Car');

	module.exports = function(app) {
		return app.use('/', router);
	};

	router.get('/', function(req, res, next) {
		res.render('index', {
			title: 'Car',
		});
		return console.log('hi');
	});

	router.get('/search', function(req, res, next) {
		var dataID = req.body.id,
			dataTime1 = req.body.time1,
			dataTime2 = req.body.time2;

		return Car.find({
				Source: dataID,
				Time: {
					$gte: ISODate(dataTime1),
					$lt: ISODate(dataTime2)
				}
			},
			function(err, carData) {
				if (err) {
					return next(err);
				}
				res.render('map', {
					title: 'Car',
					position: carData,
				});
				return console.log('shit');
			});
	});

}).call(this);
