// Generated by CoffeeScript 1.4.0
(function() {
	var CarSchema, Schema, mongoose;

	mongoose = require('mongoose');

	Schema = mongoose.Schema;

	CarSchema = new Schema({
		Source: String,
		Latitude: Number,
		Longitude: Number,
		Name: String,
		Time: Date,
		Speed: Number,
		Course: Number,
		Altitude: Number,
		Comment: String
	});

	/*CarSchema.virtual('date').get((function() {
		return this._id.getTimestamp();
	}));*/

	mongoose.model('Car', CarSchema);

}).call(this);
